### ISSUE TITLE
Review of last usenet-drive version v0.0.90

### ISSUE THREAD

**Issue by MythodeaLoL** [javi11/usenet-drive#121]
Following the posts in the last issue #99, I decided to post the tests carried out in a separate issue.

[heap (8).zip](https://github.com/javi11/usenet-drive/files/14656525/heap.8.zip)
https://github.com/javi11/usenet-drive/tree/improve-download-speed (https://github.com/javi11/usenet-drive/commit/37a3952e8851d1ecb22db0ae9999bc4f4b170a16)

```batch
{"time":"2024-03-19T17:43:53.5351358-03:00","level":"DEBUG","msg":"connecting to REDACTED:119"}
2024/03/19 17:43:54 http: panic serving [::1]:63428: runtime error: slice bounds out of range [786432:750000]
goroutine 4703 [running]:
net/http.(*conn).serve.func1()
        C:/Program Files/Go/src/net/http/server.go:1898 +0xbe
panic({0x98f000?, 0xc0001761f8?})
        C:/Program Files/Go/src/runtime/panic.go:770 +0x132
github.com/javi11/usenet-drive/internal/usenet/filereader.(*buffer).readFromNotificationDownloader(0x0?, 0x0?, 0x0?, {0xc00153e000?, 0xc182e?, 0x60d?}, 0xc0000772f0?)
        C:/Workspace_Codes/usenet-drive-improve-download-speed_3/internal/usenet/filereader/buffer.go:298 +0x19a
github.com/javi11/usenet-drive/internal/usenet/filereader.(*buffer).read(0xc0003720e0, {0xc00153e000, 0x200, 0x8000}, 0x60c, 0xc0000)
        C:/Workspace_Codes/usenet-drive-improve-download-speed_3/internal/usenet/filereader/buffer.go:274 +0x614
github.com/javi11/usenet-drive/internal/usenet/filereader.(*buffer).Read(0xc0003720e0, {0xc00153e000?, 0xc00153c280?, 0xc00180b350?})
        C:/Workspace_Codes/usenet-drive-improve-download-speed_3/internal/usenet/filereader/buffer.go:189 +0x85
github.com/javi11/usenet-drive/internal/usenet/filereader.(*file).Read(0xc000360000, {0xc00153e000?, 0xc00180b3f0?, 0x1a08ff?})
        C:/Workspace_Codes/usenet-drive-improve-download-speed_3/internal/usenet/filereader/file.go:174 +0x3b
io.(*LimitedReader).Read(0xc0002fc288, {0xc00153e000?, 0x10001010002a630?, 0x15a6147a510?})
        C:/Program Files/Go/src/io/io.go:479 +0x43
io.(*LimitedReader).Read(0xc0002fc2a0, {0xc00153e000?, 0xc00153e000?, 0x0?})
        C:/Program Files/Go/src/io/io.go:479 +0x43
io.copyBuffer({0xbc3da0, 0xc0001a4170}, {0xbc3700, 0xc0002fc2a0}, {0xc00153e000, 0x8000, 0x8000})
        C:/Program Files/Go/src/io/io.go:429 +0x191
io.CopyBuffer({0xbc3da0?, 0xc0001a4170?}, {0xbc3700?, 0xc0002fc2a0?}, {0xc00153e000?, 0x1ab9bd?, 0x19f9da?})
        C:/Program Files/Go/src/io/io.go:402 +0x36
net/http.(*response).ReadFrom(0xc000372000, {0xbc3700, 0xc0002fc288})
        C:/Program Files/Go/src/net/http/server.go:594 +0x1ae
io.copyBuffer({0xbc3dc0, 0xc000372000}, {0xbc3700, 0xc0002fc288}, {0x0, 0x0, 0x0})
        C:/Program Files/Go/src/io/io.go:415 +0x151
io.Copy(...)
        C:/Program Files/Go/src/io/io.go:388
io.CopyN({0xbc3dc0, 0xc000372000}, {0x15a6156ab50, 0xc000360000}, 0x182e)
        C:/Program Files/Go/src/io/io.go:364 +0x8c
net/http.serveContent({0xbc7120, 0xc000372000}, 0xc00072a240, {0xc00011a070, 0x6b}, {0x1a08ff?, 0x93b1e0?, 0x0?}, 0xc00180b8a0, {0x15a6156ab28, ...})
        C:/Program Files/Go/src/net/http/fs.go:378 +0xd25
net/http.ServeContent({0xbc7120?, 0xc000372000?}, 0xc00072bf80?, {0xc00011a070?, 0x0?}, {0xc004d7b938?, 0x1ab6e5?, 0x0?}, {0x15a6156ab28, 0xc000360000})
        C:/Program Files/Go/src/net/http/fs.go:206 +0x76
golang.org/x/net/webdav.(*Handler).handleGetHeadPost(0xc00009e200, {0xbc7120, 0xc000372000}, 0xc00072a240)
        C:/Users/admin/go/pkg/mod/golang.org/x/net@v0.19.0/webdav/webdav.go:220 +0x551
golang.org/x/net/webdav.(*Handler).ServeHTTP(0xc00009e200, {0xbc7120, 0xc000372000}, 0xc00072a240)
        C:/Users/admin/go/pkg/mod/golang.org/x/net@v0.19.0/webdav/webdav.go:54 +0x11b
github.com/javi11/usenet-drive/internal/webdav.(*webdavServer).Start.func1({0xbc7120, 0xc000372000}, 0xc00072a000)
        C:/Workspace_Codes/usenet-drive-improve-download-speed_3/internal/webdav/server.go:55 +0x26e
net/http.HandlerFunc.ServeHTTP(0xc00002c230?, {0xbc7120?, 0xc000372000?}, 0x4b079a?)
        C:/Program Files/Go/src/net/http/server.go:2166 +0x29
net/http.(*ServeMux).ServeHTTP(0x2023b9?, {0xbc7120, 0xc000372000}, 0xc00072a000)
        C:/Program Files/Go/src/net/http/server.go:2683 +0x1ad
net/http.serverHandler.ServeHTTP({0xc00002a060?}, {0xbc7120?, 0xc000372000?}, 0x6?)
        C:/Program Files/Go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc0003b4090, {0xbc87c0, 0xc0000889c0})
        C:/Program Files/Go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 31
        C:/Program Files/Go/src/net/http/server.go:3285 +0x4b4
{"time":"2024-03-19T17:44:02.8176726-03:00","level":"DEBUG","msg":"connecting to REDACTED:119"}
```

```yaml
rclone:
  vfs_url: "http://localhost:6572"
usenet:
  # 3MB 3145728
  article_size_in_bytes: 3145728
  download:
    max_download_workers: 3
    max_retries: 8
```

Tested on 3MB and 0.75MB nzb files

In general, it seems to have behaved very well, apart from this small specific error that caused an imperfect streaming, not detecting the audio and with some image errors, other files opened normally without failures, so it must be an isolated problem. The memory worked perfectly, without overload. No negative points to present for now.

<hr></hr>

**Edit 2:**
```cmd
{"time":"2024-03-19T22:36:33.9157035-03:00","level":"DEBUG","msg":"All download retries exhausted","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED.mkv","error":"All attempts fail:\n#1: error getting body: transform: short source buffer","segment":"REDACTED@UsenetDrive"}
{"time":"2024-03-19T22:36:33.9162089-03:00","level":"ERROR","msg":"Marking file as corrupted:","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED.mkv","error":"corrupted nzb\nerror getting body: transform: short source buffer","fileName":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED.nzb"}
```
One segment doesn't seem to have downloaded correctly, it seems like something related to the buffer size, maybe it's already been fixed by you, but I'm reporting it anyway.

**Comment by javi11** [comment]
Thanks for the info. I found a lot of wrong  implementations around the buffer and the Usenet connection that I already fix it, I’m just updating the tests, hopefully it will be available for middle next week or sooner ;)

**Comment by MythodeaLoL** [comment]
[heap (9).zip](https://github.com/javi11/usenet-drive/files/14729357/heap.9.zip)
https://github.com/javi11/usenet-drive/tree/improve-download-speed (https://github.com/javi11/usenet-drive/commit/f975aaf96616b4b234730402ef1830ea4c682190)

```cmd
{"time":"2024-03-22T20:21:55.8461825-03:00","level":"DEBUG","msg":"connecting to REDACTED:119"}
{"time":"2024-03-22T20:24:34.303667-03:00","level":"DEBUG","msg":"All download retries exhausted","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.mkv","error":"All attempts fail:\n#1: error starting download: error getting body: transform: short source buffer","segment":"f68fb40c-e4ef-4bef-aa6b-REDACTED@UsenetDrive"}
{"time":"2024-03-22T20:24:34.303667-03:00","level":"ERROR","msg":"Marking file as corrupted:","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.mkv","error":"corrupted nzb\nerror starting download: error getting body: transform: short source buffer","fileName":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.nzb"}
{"time":"2024-03-22T20:24:34.3073308-03:00","level":"DEBUG","msg":"Retrying download","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.mkv","error":"error getting body: EOF","segment":"f68fb40c-e4ef-4bef-aa6b-REDACTED@UsenetDrive","retry":0}
{"time":"2024-03-22T20:24:34.3073308-03:00","level":"DEBUG","msg":"Closing connection","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.mkv","error":"error getting body: EOF","segment":"f68fb40c-e4ef-4bef-aa6b-REDACTED@UsenetDrive","retry":0,"error_connection_host":"REDACTED","error_connection_created_at":"2024-03-22T20:21:54.69137-03:00"}
{"time":"2024-03-22T20:24:34.3333339-03:00","level":"DEBUG","msg":"All download retries exhausted","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.mkv","error":"All attempts fail:\n#1: error starting download: error getting body: transform: short source buffer","segment":"65bc655c-95d3-45bc-a6f3-REDACTED@UsenetDrive"}
{"time":"2024-03-22T20:24:34.3333339-03:00","level":"ERROR","msg":"Marking file as corrupted:","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.mkv","error":"corrupted nzb\nerror starting download: error getting body: transform: short source buffer","fileName":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.nzb"}
{"time":"2024-03-22T20:24:34.3338395-03:00","level":"DEBUG","msg":"Retrying download","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.mkv","error":"error getting body: EOF","segment":"65bc655c-95d3-45bc-a6f3-REDACTED@UsenetDrive","retry":0}
{"time":"2024-03-22T20:24:34.3343653-03:00","level":"DEBUG","msg":"Closing connection","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.mkv","error":"error getting body: EOF","segment":"65bc655c-95d3-45bc-a6f3-REDACTED@UsenetDrive","retry":0,"error_connection_host":"REDACTED","error_connection_created_at":"2024-03-22T20:21:53.8531632-03:00"}
{"time":"2024-03-22T20:24:34.4087735-03:00","level":"DEBUG","msg":"Retrying download","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.mkv","error":"error getting body: EOF","segment":"f68fb40c-e4ef-4bef-aa6b-REDACTED@UsenetDrive","retry":1}
{"time":"2024-03-22T20:24:34.4092804-03:00","level":"DEBUG","msg":"Closing connection","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.mkv","error":"error getting body: EOF","segment":"f68fb40c-e4ef-4bef-aa6b-REDACTED@UsenetDrive","retry":1,"error_connection_host":"REDACTED","error_connection_created_at":"2024-03-22T20:21:55.8461825-03:00"}
{"time":"2024-03-22T20:24:34.4371359-03:00","level":"DEBUG","msg":"Retrying download","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.mkv","error":"error getting body: EOF","segment":"65bc655c-95d3-45bc-a6f3-REDACTED@UsenetDrive","retry":1}
{"time":"2024-03-22T20:24:34.4371359-03:00","level":"DEBUG","msg":"Closing connection","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.mkv","error":"error getting body: EOF","segment":"65bc655c-95d3-45bc-a6f3-REDACTED@UsenetDrive","retry":1,"error_connection_host":"REDACTED","error_connection_created_at":"2024-03-22T20:21:53.8531632-03:00"}
{"time":"2024-03-22T20:24:34.5139032-03:00","level":"DEBUG","msg":"Retrying download","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.mkv","error":"error getting body: EOF","segment":"f68fb40c-e4ef-4bef-aa6b-REDACTED@UsenetDrive","retry":2}
{"time":"2024-03-22T20:24:34.5144127-03:00","level":"DEBUG","msg":"Closing connection","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.mkv","error":"error getting body: EOF","segment":"f68fb40c-e4ef-4bef-aa6b-REDACTED@UsenetDrive","retry":2,"error_connection_host":"REDACTED","error_connection_created_at":"2024-03-22T20:21:54.69137-03:00"}
{"time":"2024-03-22T20:24:34.5447094-03:00","level":"DEBUG","msg":"Retrying download","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.mkv","error":"error getting body: EOF","segment":"65bc655c-95d3-45bc-a6f3-REDACTED@UsenetDrive","retry":2}
{"time":"2024-03-22T20:24:34.5450013-03:00","level":"DEBUG","msg":"Closing connection","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.mkv","error":"error getting body: EOF","segment":"65bc655c-95d3-45bc-a6f3-REDACTED@UsenetDrive","retry":2,"error_connection_host":"REDACTED","error_connection_created_at":"2024-03-22T20:21:53.8531632-03:00"}
{"time":"2024-03-22T20:24:34.6191748-03:00","level":"DEBUG","msg":"connecting to REDACTED:119"}
{"time":"2024-03-22T20:24:34.6532166-03:00","level":"DEBUG","msg":"connecting to REDACTED:119"}
{"time":"2024-03-22T20:24:34.9663392-03:00","level":"DEBUG","msg":"connecting to REDACTED:119"}
{"time":"2024-03-22T20:24:46.4316189-03:00","level":"DEBUG","msg":"Retrying download","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.mkv","error":"error getting body: EOF","segment":"00542d87-f436-4367-8049-REDACTED@UsenetDrive","retry":0}
{"time":"2024-03-22T20:24:46.4316189-03:00","level":"DEBUG","msg":"Closing connection","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 3MB\\REDACTED-720p.mkv","error":"error getting body: EOF","segment":"00542d87-f436-4367-8049-REDACTED@UsenetDrive","retry":0,"error_connection_host":"REDACTED","error_connection_created_at":"2024-03-22T20:21:53.8531632-03:00"}
2024/03/22 20:24:55 http: panic serving [::1]:57756: runtime error: invalid memory address or nil pointer dereference
goroutine 2118 [running]:
net/http.(*conn).serve.func1()
        C:/Program Files/Go/src/net/http/server.go:1898 +0xbe
panic({0x148a540?, 0x13d05e0?})
        C:/Program Files/Go/src/runtime/panic.go:770 +0x132
github.com/mnightingale/rapidyenc.(*Decoder).Read(0xc0064940f0, {0xc0002090b3, 0x6f4d, 0xd036a5?})
        C:/Users/admin/go/pkg/mod/github.com/mnightingale/rapidyenc@v0.0.0-20240115193859-354d8545b0ff/decoder.go:172 +0x3b0
github.com/javi11/usenet-drive/pkg/nntpcli.(*DecoderReader).Read(0xc00085a090, {0xc0002090b3?, 0x144ed01?, 0x0?})
        C:/Workspace_Codes/usenet-drive-improve-download-speed_4/pkg/nntpcli/connection.go:212 +0x28
github.com/neilotoole/streamcache.(*Stream).readFinal(0xc0000ce180, 0xc00068dcc0, {0xc0002090b3, 0x6f4d, 0x6f4d}, 0x300000)
        C:/Users/admin/go/pkg/mod/github.com/neilotoole/streamcache@v0.3.5/streamcache.go:384 +0x3a2
github.com/neilotoole/streamcache.(*Stream).readMain(0xc0000ce180, 0xc00068dcc0, {0xc0002090b3, 0x6f4d, 0x6f4d}, 0x300000)
        C:/Users/admin/go/pkg/mod/github.com/neilotoole/streamcache@v0.3.5/streamcache.go:204 +0x1da
github.com/neilotoole/streamcache.(*Reader).Read(0xc00068dcc0, {0xc0002090b3?, 0x6f4d?, 0x6f4d?})
        C:/Users/admin/go/pkg/mod/github.com/neilotoole/streamcache@v0.3.5/streamcache.go:639 +0x86
io.ReadAtLeast({0x1723200, 0xc00068dcc0}, {0xc000208000, 0x8000, 0x8000}, 0x8000)
        C:/Program Files/Go/src/io/io.go:335 +0x90
io.ReadFull(...)
        C:/Program Files/Go/src/io/io.go:354
github.com/javi11/usenet-drive/internal/usenet/filereader.(*downloadManager).ReadAt(0xc00084e000, {0x1727858?, 0xc000073b80?}, {0xc000208000, 0x8000, 0x8000}, 0x2fef4d)
        C:/Workspace_Codes/usenet-drive-improve-download-speed_4/internal/usenet/filereader/downloadmanager.go:106 +0x22b
github.com/javi11/usenet-drive/internal/usenet/filereader.(*buffer).read(0xc000480000, {0xc000208000, 0x8000, 0x8000}, 0x52f, 0x2fef4d)
        C:/Workspace_Codes/usenet-drive-improve-download-speed_4/internal/usenet/filereader/buffer.go:243 +0x37a
github.com/javi11/usenet-drive/internal/usenet/filereader.(*buffer).Read(0xc000480000, {0xc000208000?, 0xc0000a0018?, 0xc000208000?})
        C:/Workspace_Codes/usenet-drive-improve-download-speed_4/internal/usenet/filereader/buffer.go:188 +0x85
github.com/javi11/usenet-drive/internal/usenet/filereader.(*file).Read(0xc00148a690, {0xc000208000?, 0x14563e0?, 0xef6601?})
        C:/Workspace_Codes/usenet-drive-improve-download-speed_4/internal/usenet/filereader/file.go:174 +0x3b
io.(*LimitedReader).Read(0xc0000a0cc0, {0xc000208000?, 0xd09a1f?, 0xc0000c6028?})
        C:/Program Files/Go/src/io/io.go:479 +0x43
io.copyBuffer({0x17237c0, 0xc0000c6028}, {0x1722760, 0xc0000a0cc0}, {0x0, 0x0, 0x0})
        C:/Program Files/Go/src/io/io.go:429 +0x191
io.Copy(...)
        C:/Program Files/Go/src/io/io.go:388
net.genericReadFrom(0x13cf960?, {0x1722760, 0xc0000a0cc0})
        C:/Program Files/Go/src/net/net.go:689 +0x58
net.(*TCPConn).readFrom(0xc000062458, {0x1722760, 0xc0000a0cc0})
        C:/Program Files/Go/src/net/tcpsock_posix.go:54 +0x47
net.(*TCPConn).ReadFrom(0xc000062458, {0x1722760?, 0xc0000a0cc0?})
        C:/Program Files/Go/src/net/tcpsock.go:130 +0x30
net/http.(*response).ReadFrom(0xc0007d6000, {0x1722760, 0xc0000a0cc0})
        C:/Program Files/Go/src/net/http/server.go:606 +0x31e
io.copyBuffer({0x1722e20, 0xc0007d6000}, {0x1722760, 0xc0000a0cc0}, {0x0, 0x0, 0x0})
        C:/Program Files/Go/src/io/io.go:415 +0x151
io.Copy(...)
        C:/Program Files/Go/src/io/io.go:388
io.CopyN({0x1722e20, 0xc0007d6000}, {0x223fbcc44c0, 0xc00148a690}, 0x4000000)
        C:/Program Files/Go/src/io/io.go:364 +0x8c
net/http.serveContent({0x1726180, 0xc0007d6000}, 0xc0007e2240, {0xc0000dc2a0, 0x6b}, {0xd008ff?, 0x149a360?, 0x0?}, 0xc0002178a0, {0x223fbcc4498, ...})
        C:/Program Files/Go/src/net/http/fs.go:378 +0xd25
net/http.ServeContent({0x1726180?, 0xc0007d6000?}, 0xc0007e3f80?, {0xc0000dc2a0?, 0x0?}, {0xc004425938?, 0xd0b6e5?, 0x0?}, {0x223fbcc4498, 0xc00148a690})
        C:/Program Files/Go/src/net/http/fs.go:206 +0x76
golang.org/x/net/webdav.(*Handler).handleGetHeadPost(0xc0000bc100, {0x1726180, 0xc0007d6000}, 0xc0007e2240)
        C:/Users/admin/go/pkg/mod/golang.org/x/net@v0.19.0/webdav/webdav.go:220 +0x551
golang.org/x/net/webdav.(*Handler).ServeHTTP(0xc0000bc100, {0x1726180, 0xc0007d6000}, 0xc0007e2240)
        C:/Users/admin/go/pkg/mod/golang.org/x/net@v0.19.0/webdav/webdav.go:54 +0x11b
github.com/javi11/usenet-drive/internal/webdav.(*webdavServer).Start.func1({0x1726180, 0xc0007d6000}, 0xc0007e2000)
        C:/Workspace_Codes/usenet-drive-improve-download-speed_4/internal/webdav/server.go:54 +0x26e
net/http.HandlerFunc.ServeHTTP(0xc00008d340?, {0x1726180?, 0xc0007d6000?}, 0x101079a?)
        C:/Program Files/Go/src/net/http/server.go:2166 +0x29
net/http.(*ServeMux).ServeHTTP(0xd623b9?, {0x1726180, 0xc0007d6000}, 0xc0007e2000)
        C:/Program Files/Go/src/net/http/server.go:2683 +0x1ad
net/http.serverHandler.ServeHTTP({0xc00078a1b0?}, {0x1726180?, 0xc0007d6000?}, 0x6?)
        C:/Program Files/Go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc0001481b0, {0x1727820, 0xc0001c67e0})
        C:/Program Files/Go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 39
        C:/Program Files/Go/src/net/http/server.go:3285 +0x4b4
{"time":"2024-03-22T20:25:08.3696165-03:00","level":"DEBUG","msg":"connecting to REDACTED:119"}
{"time":"2024-03-22T20:26:29.5294753-03:00","level":"DEBUG","msg":"connecting to REDACTED:119"}
{"time":"2024-03-22T20:27:05.7545991-03:00","level":"DEBUG","msg":"connecting to REDACTED:119"}
{"time":"2024-03-22T20:27:15.8561976-03:00","level":"DEBUG","msg":"connecting to REDACTED:119"}
{"time":"2024-03-22T20:29:17.0434031-03:00","level":"DEBUG","msg":"connecting to REDACTED:119"}
{"time":"2024-03-22T20:29:17.0434031-03:00","level":"DEBUG","msg":"connecting to REDACTED:119"}
{"time":"2024-03-22T20:29:47.2667324-03:00","level":"DEBUG","msg":"connecting to REDACTED:119"}
{"time":"2024-03-22T20:30:17.6316586-03:00","level":"DEBUG","msg":"connecting to REDACTED:119"}
{"time":"2024-03-22T20:30:17.6327112-03:00","level":"DEBUG","msg":"connecting to REDACTED:119"}
{"time":"2024-03-22T20:35:37.0794211-03:00","level":"INFO","msg":"Success","time":"2024-03-22T20:35:37.0794211-03:00","latency":3086500,"method":"GET","path":"/debug/pprof/heap","status":200,"ip":"::1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"}
```

I tested the videos and did some seeks, after a while I noticed the errors in the console.

**Comment by javi11** [comment]
Could you share your configuration to try reproducing this?

**Comment by MythodeaLoL** [comment]
> Could you share your configuration to try reproducing this?

rclone:
```cmd
config_rclone\usenet_rclone.exe mount ^
--config="config_rclone\rclone.conf" ^
--cache-dir="config_rclone\cache_local" ^
--cache-db-purge ^
-vv ^
--vfs-cache-mode full ^
--vfs-cache-max-age 48h ^
--vfs-cache-max-size 100G ^
 ^
--vfs-read-chunk-size=64M ^
--vfs-read-chunk-size-limit=512M ^
 ^
--buffer-size=0 ^
--dir-cache-time 10s --poll-interval 1s ^
 ^
--network-mode ^
--volname="Usenet_RClone" ^
--stats 5s ^
--stats-one-line ^
--progress ^
 ^
 ^
--rc ^
--rc-addr localhost:6572 ^
 ^
usenet:/ U:\
```

usenet:
same config...
```yaml
root_path: "G://Drives compartilhados//U Drive//Root_NZBs"
webdav_port: 8080
api_port: 8081
db_path: ".//config_usenet//usenet-drive.db"
log_path: ".//config_usenet//usenet-logs.txt"

debug: true  
rclone:
  vfs_url: "http://localhost:6572"
usenet:
  # 3MB 3145728
  article_size_in_bytes: 3145728
  download:
    max_download_workers: 3
    max_retries: 8
```
@javi11

**Comment by MythodeaLoL** [comment]
[heap (10).zip](https://github.com/javi11/usenet-drive/files/14750981/heap.10.zip)
https://github.com/javi11/usenet-drive/tree/improve-download-speed (https://github.com/javi11/usenet-drive/commit/e980f507ea485d63d1475732f62ab4259c561faf)

This latest revision is using an exorbitant amount of RAM, I saw the usenet-drive's RAM go to more than 11GB, with a simple copy, of a 4GB file.

**Comment by MythodeaLoL** [comment]
Debug logs of the last(https://github.com/javi11/usenet-drive/issues/121#issuecomment-2019198465) message here, **Edit 3**.

[heap (11).zip](https://github.com/javi11/usenet-drive/files/14794588/heap.11.zip)
https://github.com/javi11/usenet-drive/tree/improve-download-speed (https://github.com/javi11/usenet-drive/commit/e980f507ea485d63d1475732f62ab4259c561faf)

**Logs:**
```cmd
{"time":"2024-03-28T16:32:24.5852059-03:00","level":"INFO","msg":"Starting Usenet Drive improve-download-speed-5"}
{"time":"2024-03-28T16:32:24.5945636-03:00","level":"INFO","msg":"Config parameters:","config":{"LogPath":".//config_usenet//usenet-logs.txt","RootPath":"G://Drives compartilhados//U Drive//Root_NZBs","WebDavPort":"8080","ApiPort":"8081","Usenet":{"Download":{"MaxDownloadWorkers":5,"MaxRetries":15,"Providers":[{"Host":"REDACTED","Port":443,"Username":"REDACTED","TLS":true,"MaxConnections":50,"InsecureSSL":false,"Id":""}]},"Upload":{"DryRun":false,"FileAllowlist":[".mkv",".mp4",".avi",".ts"],"MaxRetries":8,"Groups":["alt.binaries"],"Providers":[{"Host":"news.REDACTED","Port":563,"Username":"REDACTED","TLS":true,"MaxConnections":50,"InsecureSSL":false,"Id":""}]},"FakeConnections":false,"ArticleSizeInBytes":3145728,"MaxConnectionIdleTimeInMinutes":30,"MaxConnectionTTLInMinutes":60},"DBPath":".//config_usenet//usenet-drive.db","Rclone":{"VFSUrl":"http://localhost:6572"},"Debug":true}}
{"time":"2024-03-28T16:32:24.6024211-03:00","level":"INFO","msg":"WebDav server started at http://localhost:8080"}
{"time":"2024-03-28T16:32:24.6024211-03:00","level":"INFO","msg":"Api controller started at http://localhost:8081"}
{"time":"2024-03-28T16:32:45.075494-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-28T16:32:45.0760135-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-28T16:32:45.0760135-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-28T16:32:45.075494-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-28T16:32:45.0760135-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-28T16:32:45.0760135-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-28T16:32:47.358649-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
{"time":"2024-03-28T16:32:47.5782162-03:00","level":"DEBUG","msg":"connecting to REDACTED:443"}
2024/03/28 16:33:12 http: panic serving [::1]:63300: runtime error: invalid memory address or nil pointer dereference
goroutine 2977 [running]:
net/http.(*conn).serve.func1()
        C:/Program Files/Go/src/net/http/server.go:1898 +0xbe
panic({0x95b460?, 0x8a15e0?})
        C:/Program Files/Go/src/runtime/panic.go:770 +0x132
github.com/mnightingale/rapidyenc.(*Decoder).Read(0xc0000bc5a0, {0xc001939bdd, 0x2423, 0x1d36a5?})
        C:/Users/admin/go/pkg/mod/github.com/mnightingale/rapidyenc@v0.0.0-20240115193859-354d8545b0ff/decoder.go:172 +0x3b0
github.com/javi11/usenet-drive/pkg/nntpcli.(*DecoderReader).Read(0xc00280c180, {0xc001939bdd?, 0xc0005fcd70?, 0xc0001900a0?})
        C:/Workspace_Codes/usenet-drive-improve-download-speed_5/pkg/nntpcli/connection.go:212 +0x28
github.com/neilotoole/streamcache.(*Stream).readFinal(0xc0006a43c0, 0xc000248a00, {0xc001939bdd, 0x2423, 0x2423}, 0xb71b0)
        C:/Users/admin/go/pkg/mod/github.com/neilotoole/streamcache@v0.3.5/streamcache.go:384 +0x3a2
github.com/neilotoole/streamcache.(*Stream).readMain(0xc0006a43c0, 0xc000248a00, {0xc001939bdd, 0x2423, 0x2423}, 0xb71b0)
        C:/Users/admin/go/pkg/mod/github.com/neilotoole/streamcache@v0.3.5/streamcache.go:204 +0x1da
github.com/neilotoole/streamcache.(*Reader).Read(0xc000248a00, {0xc001939bdd?, 0x2423?, 0x2423?})
        C:/Users/admin/go/pkg/mod/github.com/neilotoole/streamcache@v0.3.5/streamcache.go:639 +0x86
io.ReadAtLeast({0xbf43c0, 0xc000248a00}, {0xc001934000, 0x8000, 0x8000}, 0x8000)
        C:/Program Files/Go/src/io/io.go:335 +0x90
io.ReadFull(...)
        C:/Program Files/Go/src/io/io.go:354
github.com/javi11/usenet-drive/internal/usenet/filereader.(*downloadManager).ReadAt(0xc001cab4a0, {0xbf8a18, 0xc000239950}, {0xc001934000, 0x8000, 0x8000}, 0xb15d3)
        C:/Workspace_Codes/usenet-drive-improve-download-speed_5/internal/usenet/filereader/downloadmanager.go:132 +0x399
github.com/javi11/usenet-drive/internal/usenet/filereader.(*buffer).read(0xc0001c85b0, {0xc001934000, 0x8000, 0x8000}, 0x1054, 0xb15d3)
        C:/Workspace_Codes/usenet-drive-improve-download-speed_5/internal/usenet/filereader/buffer.go:243 +0x37a
github.com/javi11/usenet-drive/internal/usenet/filereader.(*buffer).Read(0xc0001c85b0, {0xc001934000?, 0xc000008480?, 0xc001934000?})
        C:/Workspace_Codes/usenet-drive-improve-download-speed_5/internal/usenet/filereader/buffer.go:188 +0x85
github.com/javi11/usenet-drive/internal/usenet/filereader.(*file).Read(0xc0000bc0f0, {0xc001934000?, 0x9273a0?, 0x3c6601?})
        C:/Workspace_Codes/usenet-drive-improve-download-speed_5/internal/usenet/filereader/file.go:174 +0x3b
io.(*LimitedReader).Read(0xc0006b5b00, {0xc001934000?, 0x1d9a1f?, 0xc001908060?})
        C:/Program Files/Go/src/io/io.go:479 +0x43
io.copyBuffer({0xbf4980, 0xc001908060}, {0xbf3920, 0xc0006b5b00}, {0x0, 0x0, 0x0})
        C:/Program Files/Go/src/io/io.go:429 +0x191
io.Copy(...)
        C:/Program Files/Go/src/io/io.go:388
net.genericReadFrom(0x8a0960?, {0xbf3920, 0xc0006b5b00})
        C:/Program Files/Go/src/net/net.go:689 +0x58
net.(*TCPConn).readFrom(0xc0002361d8, {0xbf3920, 0xc0006b5b00})
        C:/Program Files/Go/src/net/tcpsock_posix.go:54 +0x47
net.(*TCPConn).ReadFrom(0xc0002361d8, {0xbf3920?, 0xc0006b5b00?})
        C:/Program Files/Go/src/net/tcpsock.go:130 +0x30
net/http.(*response).ReadFrom(0xc000846000, {0xbf3920, 0xc0006b5b00})
        C:/Program Files/Go/src/net/http/server.go:606 +0x31e
io.copyBuffer({0xbf3fe0, 0xc000846000}, {0xbf3920, 0xc0006b5b00}, {0x0, 0x0, 0x0})
        C:/Program Files/Go/src/io/io.go:415 +0x151
io.Copy(...)
        C:/Program Files/Go/src/io/io.go:388
io.CopyN({0xbf3fe0, 0xc000846000}, {0x21e7ae55718, 0xc0000bc0f0}, 0x8000000)
        C:/Program Files/Go/src/io/io.go:364 +0x8c
net/http.serveContent({0xbf7340, 0xc000846000}, 0xc000154d80, {0xc000026140, 0x50}, {0x1d08ff?, 0x96b280?, 0x0?}, 0xc0005fd8a0, {0x21e7ae556f0, ...})
        C:/Program Files/Go/src/net/http/fs.go:378 +0xd25
net/http.ServeContent({0xbf7340?, 0xc000846000?}, 0xc000155f80?, {0xc000026140?, 0x0?}, {0xc0029c7938?, 0x1db6e5?, 0x0?}, {0x21e7ae556f0, 0xc0000bc0f0})
        C:/Program Files/Go/src/net/http/fs.go:206 +0x76
golang.org/x/net/webdav.(*Handler).handleGetHeadPost(0xc000070200, {0xbf7340, 0xc000846000}, 0xc000154d80)
        C:/Users/admin/go/pkg/mod/golang.org/x/net@v0.19.0/webdav/webdav.go:220 +0x551
golang.org/x/net/webdav.(*Handler).ServeHTTP(0xc000070200, {0xbf7340, 0xc000846000}, 0xc000154d80)
        C:/Users/admin/go/pkg/mod/golang.org/x/net@v0.19.0/webdav/webdav.go:54 +0x11b
github.com/javi11/usenet-drive/internal/webdav.(*webdavServer).Start.func1({0xbf7340, 0xc000846000}, 0xc0001546c0)
        C:/Workspace_Codes/usenet-drive-improve-download-speed_5/internal/webdav/server.go:54 +0x26e
net/http.HandlerFunc.ServeHTTP(0xc00022cf30?, {0xbf7340?, 0xc000846000?}, 0x4e079a?)
        C:/Program Files/Go/src/net/http/server.go:2166 +0x29
net/http.(*ServeMux).ServeHTTP(0x2323b9?, {0xbf7340, 0xc000846000}, 0xc0001546c0)
        C:/Program Files/Go/src/net/http/server.go:2683 +0x1ad
net/http.serverHandler.ServeHTTP({0xc00880c0c0?}, {0xbf7340?, 0xc000846000?}, 0x6?)
        C:/Program Files/Go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc0002222d0, {0xbf89e0, 0xc00002a9f0})
        C:/Program Files/Go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 40
        C:/Program Files/Go/src/net/http/server.go:3285 +0x4b4
2024/03/28 16:33:22 http: panic serving [::1]:63318: runtime error: invalid memory address or nil pointer dereference
goroutine 4157 [running]:
net/http.(*conn).serve.func1()
        C:/Program Files/Go/src/net/http/server.go:1898 +0xbe
panic({0x95b460?, 0x8a15e0?})
        C:/Program Files/Go/src/runtime/panic.go:770 +0x132
github.com/mnightingale/rapidyenc.(*Decoder).Read(0xc0000bc2d0, {0xc00267d9dd, 0x2623, 0x1d36a5?})
        C:/Users/admin/go/pkg/mod/github.com/mnightingale/rapidyenc@v0.0.0-20240115193859-354d8545b0ff/decoder.go:172 +0x3b0
github.com/javi11/usenet-drive/pkg/nntpcli.(*DecoderReader).Read(0xc001762180, {0xc00267d9dd?, 0xc0005fcd70?, 0xc0000c8090?})
        C:/Workspace_Codes/usenet-drive-improve-download-speed_5/pkg/nntpcli/connection.go:212 +0x28
github.com/neilotoole/streamcache.(*Stream).readFinal(0xc000638300, 0xc0006b6500, {0xc00267d9dd, 0x2623, 0x2623}, 0xb71b0)
        C:/Users/admin/go/pkg/mod/github.com/neilotoole/streamcache@v0.3.5/streamcache.go:384 +0x3a2
github.com/neilotoole/streamcache.(*Stream).readMain(0xc000638300, 0xc0006b6500, {0xc00267d9dd, 0x2623, 0x2623}, 0xb71b0)
        C:/Users/admin/go/pkg/mod/github.com/neilotoole/streamcache@v0.3.5/streamcache.go:204 +0x1da
github.com/neilotoole/streamcache.(*Reader).Read(0xc0006b6500, {0xc00267d9dd?, 0x2623?, 0x2623?})
        C:/Users/admin/go/pkg/mod/github.com/neilotoole/streamcache@v0.3.5/streamcache.go:639 +0x86
io.ReadAtLeast({0xbf43c0, 0xc0006b6500}, {0xc002678000, 0x8000, 0x8000}, 0x8000)
        C:/Program Files/Go/src/io/io.go:335 +0x90
io.ReadFull(...)
        C:/Program Files/Go/src/io/io.go:354
github.com/javi11/usenet-drive/internal/usenet/filereader.(*downloadManager).ReadAt(0xc001903270, {0xbf8a18, 0xc000710dc0}, {0xc002678000, 0x8000, 0x8000}, 0xb17d3)
        C:/Workspace_Codes/usenet-drive-improve-download-speed_5/internal/usenet/filereader/downloadmanager.go:132 +0x399
github.com/javi11/usenet-drive/internal/usenet/filereader.(*buffer).read(0xc0001984e0, {0xc002678000, 0x8000, 0x8000}, 0x1054, 0xb17d3)
        C:/Workspace_Codes/usenet-drive-improve-download-speed_5/internal/usenet/filereader/buffer.go:243 +0x37a
github.com/javi11/usenet-drive/internal/usenet/filereader.(*buffer).Read(0xc0001984e0, {0xc002678000?, 0x1e855c?, 0x103e560?})
        C:/Workspace_Codes/usenet-drive-improve-download-speed_5/internal/usenet/filereader/buffer.go:188 +0x85
github.com/javi11/usenet-drive/internal/usenet/filereader.(*file).Read(0xc0000ba2d0, {0xc002678000?, 0x9273a0?, 0x3c6601?})
        C:/Workspace_Codes/usenet-drive-improve-download-speed_5/internal/usenet/filereader/file.go:174 +0x3b
io.(*LimitedReader).Read(0xc0029d75d8, {0xc002678000?, 0x1d9a1f?, 0xc000194050?})
        C:/Program Files/Go/src/io/io.go:479 +0x43
io.copyBuffer({0xbf4980, 0xc000194050}, {0xbf3920, 0xc0029d75d8}, {0x0, 0x0, 0x0})
        C:/Program Files/Go/src/io/io.go:429 +0x191
io.Copy(...)
        C:/Program Files/Go/src/io/io.go:388
net.genericReadFrom(0x8a0960?, {0xbf3920, 0xc0029d75d8})
        C:/Program Files/Go/src/net/net.go:689 +0x58
net.(*TCPConn).readFrom(0xc0019080a8, {0xbf3920, 0xc0029d75d8})
        C:/Program Files/Go/src/net/tcpsock_posix.go:54 +0x47
net.(*TCPConn).ReadFrom(0xc0019080a8, {0xbf3920?, 0xc0029d75d8?})
        C:/Program Files/Go/src/net/tcpsock.go:130 +0x30
net/http.(*response).ReadFrom(0xc0008460e0, {0xbf3920, 0xc0029d75d8})
        C:/Program Files/Go/src/net/http/server.go:606 +0x31e
io.copyBuffer({0xbf3fe0, 0xc0008460e0}, {0xbf3920, 0xc0029d75d8}, {0x0, 0x0, 0x0})
        C:/Program Files/Go/src/io/io.go:415 +0x151
io.Copy(...)
        C:/Program Files/Go/src/io/io.go:388
io.CopyN({0xbf3fe0, 0xc0008460e0}, {0x21e7ae55718, 0xc0000ba2d0}, 0x8000000)
        C:/Program Files/Go/src/io/io.go:364 +0x8c
net/http.serveContent({0xbf7340, 0xc0008460e0}, 0xc0001550e0, {0xc000834000, 0x50}, {0x1d08ff?, 0x96b280?, 0x0?}, 0xc0005fd8a0, {0x21e7ae556f0, ...})
        C:/Program Files/Go/src/net/http/fs.go:378 +0xd25
net/http.ServeContent({0xbf7340?, 0xc0008460e0?}, 0xc000155f80?, {0xc000834000?, 0x0?}, {0xc0027f3938?, 0x1db6e5?, 0x0?}, {0x21e7ae556f0, 0xc0000ba2d0})
        C:/Program Files/Go/src/net/http/fs.go:206 +0x76
golang.org/x/net/webdav.(*Handler).handleGetHeadPost(0xc000070200, {0xbf7340, 0xc0008460e0}, 0xc0001550e0)
        C:/Users/admin/go/pkg/mod/golang.org/x/net@v0.19.0/webdav/webdav.go:220 +0x551
golang.org/x/net/webdav.(*Handler).ServeHTTP(0xc000070200, {0xbf7340, 0xc0008460e0}, 0xc0001550e0)
        C:/Users/admin/go/pkg/mod/golang.org/x/net@v0.19.0/webdav/webdav.go:54 +0x11b
github.com/javi11/usenet-drive/internal/webdav.(*webdavServer).Start.func1({0xbf7340, 0xc0008460e0}, 0xc000154c60)
        C:/Workspace_Codes/usenet-drive-improve-download-speed_5/internal/webdav/server.go:54 +0x26e
net/http.HandlerFunc.ServeHTTP(0xc00022cf30?, {0xbf7340?, 0xc0008460e0?}, 0x4e079a?)
        C:/Program Files/Go/src/net/http/server.go:2166 +0x29
net/http.(*ServeMux).ServeHTTP(0x2323b9?, {0xbf7340, 0xc0008460e0}, 0xc000154c60)
        C:/Program Files/Go/src/net/http/server.go:2683 +0x1ad
net/http.serverHandler.ServeHTTP({0xc0029782d0?}, {0xbf7340?, 0xc0008460e0?}, 0x6?)
        C:/Program Files/Go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc000222240, {0xbf89e0, 0xc00002a9f0})
        C:/Program Files/Go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 40
        C:/Program Files/Go/src/net/http/server.go:3285 +0x4b4
2024/03/28 16:33:24 http: panic serving [::1]:63319: runtime error: invalid memory address or nil pointer dereference
goroutine 3882 [running]:
net/http.(*conn).serve.func1()
        C:/Program Files/Go/src/net/http/server.go:1898 +0xbe
panic({0x95b460?, 0x8a15e0?})
        C:/Program Files/Go/src/runtime/panic.go:770 +0x132
github.com/mnightingale/rapidyenc.(*Decoder).Read(0xc000086780, {0xc00706d7dd, 0x2823, 0x1d36a5?})
        C:/Users/admin/go/pkg/mod/github.com/mnightingale/rapidyenc@v0.0.0-20240115193859-354d8545b0ff/decoder.go:172 +0x3b0
github.com/javi11/usenet-drive/pkg/nntpcli.(*DecoderReader).Read(0xc0000c8390, {0xc00706d7dd?, 0xc000ebed70?, 0xc0001900a0?})
        C:/Workspace_Codes/usenet-drive-improve-download-speed_5/pkg/nntpcli/connection.go:212 +0x28
github.com/neilotoole/streamcache.(*Stream).readFinal(0xc0005fe0c0, 0xc00032e550, {0xc00706d7dd, 0x2823, 0x2823}, 0xb71b0)
        C:/Users/admin/go/pkg/mod/github.com/neilotoole/streamcache@v0.3.5/streamcache.go:384 +0x3a2
github.com/neilotoole/streamcache.(*Stream).readMain(0xc0005fe0c0, 0xc00032e550, {0xc00706d7dd, 0x2823, 0x2823}, 0xb71b0)
        C:/Users/admin/go/pkg/mod/github.com/neilotoole/streamcache@v0.3.5/streamcache.go:204 +0x1da
github.com/neilotoole/streamcache.(*Reader).Read(0xc00032e550, {0xc00706d7dd?, 0x2823?, 0x2823?})
        C:/Users/admin/go/pkg/mod/github.com/neilotoole/streamcache@v0.3.5/streamcache.go:639 +0x86
io.ReadAtLeast({0xbf43c0, 0xc00032e550}, {0xc007068000, 0x8000, 0x8000}, 0x8000)
        C:/Program Files/Go/src/io/io.go:335 +0x90
io.ReadFull(...)
        C:/Program Files/Go/src/io/io.go:354
github.com/javi11/usenet-drive/internal/usenet/filereader.(*downloadManager).ReadAt(0xc001903270, {0xbf8a18, 0xc0002498b0}, {0xc007068000, 0x8000, 0x8000}, 0xb19d3)
        C:/Workspace_Codes/usenet-drive-improve-download-speed_5/internal/usenet/filereader/downloadmanager.go:132 +0x399
github.com/javi11/usenet-drive/internal/usenet/filereader.(*buffer).read(0xc0002fe1a0, {0xc007068000, 0x8000, 0x8000}, 0x1054, 0xb19d3)
        C:/Workspace_Codes/usenet-drive-improve-download-speed_5/internal/usenet/filereader/buffer.go:243 +0x37a
github.com/javi11/usenet-drive/internal/usenet/filereader.(*buffer).Read(0xc0002fe1a0, {0xc007068000?, 0x1e855c?, 0x103e560?})
        C:/Workspace_Codes/usenet-drive-improve-download-speed_5/internal/usenet/filereader/buffer.go:188 +0x85
github.com/javi11/usenet-drive/internal/usenet/filereader.(*file).Read(0xc0007865a0, {0xc007068000?, 0x9273a0?, 0x1003c6601?})
        C:/Workspace_Codes/usenet-drive-improve-download-speed_5/internal/usenet/filereader/file.go:174 +0x3b
io.(*LimitedReader).Read(0xc0037ac690, {0xc007068000?, 0x1d9a1f?, 0xc001908000?})
        C:/Program Files/Go/src/io/io.go:479 +0x43
io.copyBuffer({0xbf4980, 0xc001908000}, {0xbf3920, 0xc0037ac690}, {0x0, 0x0, 0x0})
        C:/Program Files/Go/src/io/io.go:429 +0x191
io.Copy(...)
        C:/Program Files/Go/src/io/io.go:388
net.genericReadFrom(0x8a0960?, {0xbf3920, 0xc0037ac690})
        C:/Program Files/Go/src/net/net.go:689 +0x58
net.(*TCPConn).readFrom(0xc000194088, {0xbf3920, 0xc0037ac690})
        C:/Program Files/Go/src/net/tcpsock_posix.go:54 +0x47
net.(*TCPConn).ReadFrom(0xc000194088, {0xbf3920?, 0xc0037ac690?})
        C:/Program Files/Go/src/net/tcpsock.go:130 +0x30
net/http.(*response).ReadFrom(0xc000e9e000, {0xbf3920, 0xc0037ac690})
        C:/Program Files/Go/src/net/http/server.go:606 +0x31e
io.copyBuffer({0xbf3fe0, 0xc000e9e000}, {0xbf3920, 0xc0037ac690}, {0x0, 0x0, 0x0})
        C:/Program Files/Go/src/io/io.go:415 +0x151
io.Copy(...)
        C:/Program Files/Go/src/io/io.go:388
io.CopyN({0xbf3fe0, 0xc000e9e000}, {0x21e7ae55718, 0xc0007865a0}, 0x8000000)
        C:/Program Files/Go/src/io/io.go:364 +0x8c
net/http.serveContent({0xbf7340, 0xc000e9e000}, 0xc000224360, {0xc00074a000, 0x50}, {0x1d08ff?, 0x96b280?, 0x0?}, 0xc000ebf8a0, {0x21e7ae556f0, ...})
        C:/Program Files/Go/src/net/http/fs.go:378 +0xd25
net/http.ServeContent({0xbf7340?, 0xc000e9e000?}, 0xc000225f80?, {0xc00074a000?, 0x0?}, {0xc00076b938?, 0x1db6e5?, 0x0?}, {0x21e7ae556f0, 0xc0007865a0})
        C:/Program Files/Go/src/net/http/fs.go:206 +0x76
golang.org/x/net/webdav.(*Handler).handleGetHeadPost(0xc000070200, {0xbf7340, 0xc000e9e000}, 0xc000224360)
        C:/Users/admin/go/pkg/mod/golang.org/x/net@v0.19.0/webdav/webdav.go:220 +0x551
golang.org/x/net/webdav.(*Handler).ServeHTTP(0xc000070200, {0xbf7340, 0xc000e9e000}, 0xc000224360)
        C:/Users/admin/go/pkg/mod/golang.org/x/net@v0.19.0/webdav/webdav.go:54 +0x11b
github.com/javi11/usenet-drive/internal/webdav.(*webdavServer).Start.func1({0xbf7340, 0xc000e9e000}, 0xc000224000)
        C:/Workspace_Codes/usenet-drive-improve-download-speed_5/internal/webdav/server.go:54 +0x26e
net/http.HandlerFunc.ServeHTTP(0xc00022cf30?, {0xbf7340?, 0xc000e9e000?}, 0x4e079a?)
        C:/Program Files/Go/src/net/http/server.go:2166 +0x29
net/http.(*ServeMux).ServeHTTP(0x2323b9?, {0xbf7340, 0xc000e9e000}, 0xc000224000)
        C:/Program Files/Go/src/net/http/server.go:2683 +0x1ad
net/http.serverHandler.ServeHTTP({0xc00280c390?}, {0xbf7340?, 0xc000e9e000?}, 0x6?)
        C:/Program Files/Go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc00078e090, {0xbf89e0, 0xc00002a9f0})
        C:/Program Files/Go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 40
        C:/Program Files/Go/src/net/http/server.go:3285 +0x4b4
{"time":"2024-03-28T16:33:42.570375-03:00","level":"INFO","msg":"Success","time":"2024-03-28T16:33:42.570375-03:00","latency":3355800,"method":"GET","path":"/debug/pprof/heap","status":200,"ip":"::1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
{"time":"2024-03-28T16:33:42.570375-03:00","level":"INFO","msg":"Success","time":"2024-03-28T16:33:42.570375-03:00","latency":3355800,"method":"GET","path":"/debug/pprof/heap","status":200,"ip":"::1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
{"time":"2024-03-28T16:42:24.9102675-03:00","level":"DEBUG","msg":"Retrying download","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 0.75MB\\A._REDACTED_.mkv","error":"error getting body: EOF","segment":"REDACTED-dca1-44fb-9050-REDACTED@UsenetDrive","retry":0}
{"time":"2024-03-28T16:42:24.9102675-03:00","level":"DEBUG","msg":"Closing connection","filename":"G:\\Drives compartilhados\\U Drive\\Root_NZBs\\TESTE 0.75MB\\A._REDACTED_.mkv","error":"error getting body: EOF","segment":"REDACTED-dca1-44fb-9050-REDACTED@UsenetDrive","retry":0,"error_connection_host":"REDACTED","error_connection_created_at":"2024-03-28T16:32:45.075494-03:00"}
```
I noticed that the player continued playing the video, usenet-drive in this specific case still continued running, but in others, as previously reported, it was terminated. Note the last logs, I noticed after having already generated the debug, that it gave these errors of "error getting body", this apparently caused a stuck pause in the player, which started playing again after a few seconds.

NZB File: (8.5GB mkv)
```XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nzb PUBLIC "-//newzBin//DTD NZB 1.1//EN" "http://www.newzbin.com/DTD/nzb/nzb-1.1.dtd">
<nzb xmlns="http://www.newzbin.com/DTD/2003/nzb">
  <head>
    <meta type="file_size">8739817237</meta>
    <meta type="mod_time">2024-02-28 17:06:32</meta>
    <meta type="file_extension">.mkv</meta>
    <meta type="file_name">A._REDACTED_.mkv</meta>
    <meta type="chunk_size">750000</meta>
  </head>
  <file poster="alt.binaries" date="1709150794852" subject="[1/1] - &#34;REDACTED-61b8-41e7-8dc2-REDACTED&#34; yEnc (1/11654)">
    <groups>
      <group>alt.binaries</group>
    </groups>
    <segments>
      <segment bytes="750000" number="1">REDACTED-a5d3-4825-a03a-REDACTED@UsenetDrive</segment>
... REDACTED ...
      <segment bytes="750000" number="11653">REDACTED-8436-4fa4-8cd0-REDACTED@UsenetDrive</segment>
      <segment bytes="67237" number="11654">REDACTED-ecc3-48cd-826f-REDACTED@UsenetDrive</segment>
    </segments>
  </file>
</nzb>
```

**rclone config:**
```batch
config_rclone\usenet_rclone.exe mount ^
--config="config_rclone\rclone.conf" ^
--cache-dir="config_rclone\cache_local" ^
--cache-db-purge ^
-vv ^
--vfs-cache-mode full ^
--vfs-cache-max-age 48h ^
--vfs-cache-max-size 100G ^
 ^
--vfs-read-chunk-size=128M ^
--vfs-read-chunk-size-limit=0 ^
--vfs-read-ahead=1M ^
 ^
--buffer-size=0 ^
--dir-cache-time 10s --poll-interval 1s ^
 ^
--network-mode ^
--volname="Usenet_RClone" ^
--stats 5s ^
--stats-one-line ^
--progress ^
 ^
 ^
--rc ^
--rc-addr localhost:6572 ^
 ^
usenet:/ U:\
```
**I didn't encounter any more problems.**

**Comment by javi11** [comment]
Cool, let me investigate this one ;)

**Comment by MythodeaLoL** [comment]
Apparently the problem(https://github.com/javi11/usenet-drive/issues/121#issuecomment-2026007459) was fixed after the last `improve-download-speed` update (https://github.com/javi11/usenet-drive/commit/198ab32ee6a730bb377950e4a54e86ebef77a0f7).

I will be monitoring, for now, without problem, in windows build.

**Comment by javi11** [comment]
Yes, I think this is the one, there is still an issue when a video is set to pause to long time, you need to close and start the video again.

**Comment by javi11** [comment]
@MythodeaLoL I just pushed to nightly the last code for download that seems stable, If you have time to check I will appreciate it :)

**Comment by MythodeaLoL** [comment]
> @MythodeaLoL I just pushed to nightly the last code for download that seems stable, If you have time to check I will appreciate it :)

Stream doesn't show any error messages, but I'm noticing certain hiccups from time to time, regardless of the file size. Apparently the download speed is low, and then suddenly increases after the player freezes.

File copying is at low speeds, around 2MB/s ~ 3MB/s on average.

At some point I noticed network spikes, after involuntary video pauses.


Copying files at low speeds I believe is not new.

When copying, the network bandwidth exceeds 400mbps and the file copy speed does not exceed 3MB/s, averaging 2MB/s.

I don't know if they are two different problems, copy x stream. But the copying problem is not new.

I really can't tell if it's something new or existing, I don't know how to help in this case, no errors are shown.

If I can help with anything else just let me know @javi11

**Comment by javi11** [comment]
Could you try the following config?

max_download_workers: 15
download.max_connections: 40
article_size_in_bytes: 1048576

With this I achieve the following speed


<img width="767" alt="Captura de pantalla 2024-04-02 a las 9 00 41" src="https://github.com/javi11/usenet-drive/assets/3855051/9e87fb3d-65bd-4ff3-a748-43863359bb3d">

![Captura de pantalla 2024-04-02 a las 9 01 01](https://github.com/javi11/usenet-drive/assets/3855051/7e413d34-701d-4065-bbcf-e339500aa17e)

**Comment by MythodeaLoL** [comment]
![image](https://github.com/javi11/usenet-drive/assets/7586648/d41d58d2-3a72-431b-845f-d5eab9c99ddf)
[heap (13).zip](https://github.com/javi11/usenet-drive/files/14841810/heap.13.zip)

```yaml
usenet:
  article_size_in_bytes: 1048576
download:
    max_download_workers: 15
    #max_buffer_size_in_mb: 50
    max_retries: 15
    providers:
        port: 443
        tls: true
        max_connections: 50
```
file uploaded using the same settings.

<hr></hr>

RaiDrive WebDav 15 connections.
![image](https://github.com/javi11/usenet-drive/assets/7586648/62b7230b-bd29-4195-9c5e-1d97e3e9410c)

By connecting using RaiDrive, directly to WebDav I get faster speeds.

using 50 download connections I achieved surprising speeds, with peaks of up to 70MB/s, similar to yours, all using RaiDrive WebDav.

Using an rclone configuration without vfs cache, I got a higher speed, on average 17MB/s+ for 50 connections, with peaks of 34MB/s, somewhat similar to RaiDrive.
It seems to be a problem with rclone, perhaps some configuration, but I used the recommended options, and mine, with vfs and they are the same. I'm going to do some more tests on rclone.

**Comment by javi11** [comment]
I will close this one since in terms of stream/download it has a pretty decent speed and there are not memory leaks anymore.
