### ISSUE TITLE
[BUG] Completely incorrect connection handling with usenight.com provider

### ISSUE THREAD

**Issue by gyurix** [javi11/usenet-drive#91]
If you try to use the software with the https://usenight.com provider, you will see that after a few minutes of active uploading a bunch of ghost connections gets created and the program stops working because of hitting the 50 connection limit of the provider, despite the fact of being limited to much less connections in the config. This provider is a very solid one supporting insanely high speeds, even in the range of 5-10Gbps for extremely cheap, so it will be great to see this tool work with them properly.

**Comment by javi11** [comment]
@gyurix could you put the log that shows the error? Probably if you hit max connections a code 502 will appear on the logs

**Comment by gyurix** [comment]
Yes, it shows up in the logs:
```
{"time":"2024-02-04T00:59:11.366235079Z","level":"ERROR","msg":"Error uploading the file","filename":"OMITTED","error":"error getting nntp connection: 482 too many connections for your user"}
{"time":"2024-02-04T00:59:11.36628115Z","level":"INFO","msg":"Upload file was discarded because an error","name":"OMITTED","err":"error getting nntp connection: 482 too many connections for your user"}
```

The easiest way to reproduce the error is to start uploading some files using rclone copy and once finished start another upload with rclone copy.

My config looks like this (with valid credentials of course):
```
root_path: /nzbs
webdav_port: 8080
api_port: 8081
db_path: /config/usenet-drive.db
usenet:
  download:
    max_download_workers: 3
    providers:
      - host: "reader.usenight.com"
        port: 563
        username: "OMITTED"
        password: "OMITTED"
        tls: true
        max_connections: 3
  upload:
    groups:
      - alt.binaries
    file_allow_list:
      - .bin
    providers:
      - host: "reader.usenight.com"
        port: 563
        username: "OMITTED"
        password: "OMITTED"
        tls: true
        max_connections: 27
```

**Comment by gyurix** [comment]
My best guess is that this provider requires us to send the QUIT nntp command to it when closing a connection, while other providers does not require that.

**Comment by javi11** [comment]
I see @gyurix, in the last version, which i´m currently testing and seems pretty stable I already implemented the QUIT command on close the connection. Could you please try that one?

**Comment by gyurix** [comment]
I updated to the latest version and this exact same issue still happens with it. With an addition of the following errors, which were not happening in earlier versions:
2024/02/04 14:26:42 http: superfluous response.WriteHeader call from golang.org/x/net/webdav.(*Handler).ServeHTTP (webdav.go:75)
2024/02/04 14:26:53 http: superfluous response.WriteHeader call from golang.org/x/net/webdav.(*Handler).ServeHTTP (webdav.go:75)

**Comment by javi11** [comment]
OK I reproduced the issue, seems that if connection is broken for some reason like an internet is down, after try to connect again the you will receive the too many connections for your user error. Thanks for it I will work on this ;)

**Comment by javi11** [comment]
@gyurix please retry with last version, I did some refactor of the connection pool. I also tried with usenet night and all went okey. Connections matched the one showed on the admin panel

<img width="858" alt="Captura de pantalla 2024-02-05 a las 12 36 20" src="https://github.com/javi11/usenet-drive/assets/3855051/a6b4fdeb-5a52-4540-89e7-2adb89f259ce">

<img width="587" alt="Captura de pantalla 2024-02-05 a las 12 36 27" src="https://github.com/javi11/usenet-drive/assets/3855051/47f05235-3c46-4e5f-b999-154812aedb33">

**Comment by gyurix** [comment]
I can't properly test it on the latest version, because I keep getting this error all the time:
http: superfluous response.WriteHeader call from golang.org/x/net/webdav.(*Handler).ServeHTTP (webdav.go:75)

**Comment by javi11** [comment]
Is this happening on the upload or the download?

**Comment by gyurix** [comment]
Upload & it happens mostly if I try to upload to the directory where I already uploaded before mostly.

**Comment by gyurix** [comment]
With these latest updates I do believe this got fixed, so we can close this issue.
